name: Release and Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Bump version and create tag
        id: versioning
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          NEW_TAG=$(npm version patch -m "ci: bump version to %s")
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/chrisRol2/renamePropMongo.git HEAD:main --follow-tags
          echo "tag_name=$NEW_TAG" >> $GITHUB_ENV

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag_name }}
          release_name: "Release ${{ env.tag_name }}"
          draft: false
          prerelease: false

  publish_to_npm:
    needs: create_release
    runs-on: ubuntu-22.04
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Asegurarse de obtener todo el historial y tags

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.2.0

      - name: Install dependencies
        run: npm install

      - name: Build bundle
        run: npm run build

      - name: Publish to npm
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
